organization:
    id: 1276ee9d-90de-45eb-b0dd-ff94508f0de4
    name: StockFishcher
project:
    id: 137c035d-424a-4417-992c-0c2a4f6f2748
    slug: circleci/3HFCvJwxHzbbGxsQTZB7GP/3QYrP3uhZNfcHUBemzZZVZ
    name: doodooo
